// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVuAU73PwuSPs5Q1y0kvlbVMMJ9pFpwFU',
    appId: '1:1088294582682:web:6b3c65c03f1524376ea223',
    messagingSenderId: '1088294582682',
    projectId: 'inet-hrm',
    authDomain: 'inet-hrm.firebaseapp.com',
    storageBucket: 'inet-hrm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXEyMuUJuxE7edAU2ceV0d9CJKONiyM6w',
    appId: '1:1088294582682:android:ecc08db59017cd056ea223',
    messagingSenderId: '1088294582682',
    projectId: 'inet-hrm',
    storageBucket: 'inet-hrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiq77icibzWJsVMDgf1xrjaqM-EODRp1A',
    appId: '1:1088294582682:ios:e5ce6addd9cbf3c36ea223',
    messagingSenderId: '1088294582682',
    projectId: 'inet-hrm',
    storageBucket: 'inet-hrm.firebasestorage.app',
    iosBundleId: 'com.example.hrmMobile',
  );
}
